### ISSUE TITLE
Find a home for the site

### ISSUE THREAD

**Issue by rogerhutchings** [rogerhutchings/balzan-website#11]
Check with Chris to see who needs the finished site

**Comment by chrislintott** [comment]
Ideally it will be linked from here : http://balzan.new.ox.ac.uk/home.shtml 
Can I get you to talk to the New College people and see if they can just redirect?

**Comment by rogerhutchings** [comment]
closed via 5104422c5c6b301bf9dda89b4d95c8f5bffdf2a4
